### ISSUE TITLE
[Install error] nimporter.NimCompileException:  cannot open file: bioseq

### ISSUE THREAD

**Issue by miguel6298** [Benjamin-Lee/vdsearch#11]
Hi, I am writing this issue since I am having the install error stated above. 

In order to install the pipeline, I created a conda environment where I installed the python version used in the study related (Python 3.8.3). Then I downloaded the needed packages and finally, I just followed the installation instructions but when I try to run $ "vdsearch --help", what I get is the following error:

![Captura desde 2023-03-07 13-12-26](https://user-images.githubusercontent.com/75429859/223418875-46fdfb0f-b677-4b1b-a64e-f1aa35407123.png)

I checked that I have installed all the packages but the error is still there. It seems to be a problem related to nimporter, but I am not sure at all. Are there any hint of which could be the solution for that problem?

Many thanks in advance.

Best regards

**Comment by Benjamin-Lee** [comment]
I will be the first to admit that installation is a hassle and appreciate the error report. Your error was the result of a missing library that I'd built as an unpublished separate project a while ago. Since it was already installed on both my personal machine and cluster, it never threw and error and I never noticed it was missing in this repo. I've fixed this in d2368a36c73eafc94eb40fdfecffc7af3d29e51d. 

Thanks for the error report!
